sudo: required
services:
  - docker

before_install:
  - docker build -t urvish91/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true urvish91/react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-907476164842"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
